export {default as Cardigan1 } from './Cardigan1.jpg'
export {default as Cardigan2 } from './Cardigan2.jpg'
export {default as Cardigan3 } from './Cardigan3.jpg'
export {default as Cardigan4 } from './Cardigan4.jpg'
export {default as HNM1 } from './hnm1.jpeg'
export {default as Noise} from './nnnoise.svg'